frase=str(input('digite seu nome completo:'))
frase = frase.upper()
print('nome maiusculo:',frase)
frase = frase.lower()
print('nome minusculo:',frase)
tiraEspaço = len(frase.replace(" ",""))
print('letras totais:',tiraEspaço)
primeiroNome=frase.split()
print('primeiro nome:',primeiroNome[0])
print('letras primeiro nome:',len(primeiroNome[0]))
