print('programa básico de soma. \n')
num1=int(input('digite o primeiro numero a ser somado :'))
num2=int(input('digite o segundo numero a ser somado :'))
resultado=(num1+num2)
print('soma dos 2 numeros :', resultado)
